name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push the Docker image
        env:
          CF_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/csdp-report-image-github-action:example-reported-image
        run: |
          docker build . --file Dockerfile --tag $CF_IMAGE && docker push $CF_IMAGE
      - name: report image by action
        with:
          CF_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/csdp-report-image-github-action:example-reported-image
          CF_ENRICHERS: "jira, git"
          CF_HOST: "https://mr-5f04515c6f790a046303eb5a-298e2ae.cf-op.com"
          CF_API_KEY: ${{ secrets.CF_TOKEN }}
          
          #USE this if you have setup integrations
          CF_CONTAINER_REGISTRY_INTEGRATION: "dockerhub"
          CF_JIRA_INTEGRATION: "jira"

          #use this if you don't have a docker integration setup
          #CF_DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          #CF_DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          
          #use this if you dont' have a jira intergration setup
          #"CF_JIRA_API_TOKEN": ${{ secrets.JIRA_TOKEN }}
          #"CF_JIRA_HOST_URL": "https://codefresh-io.atlassian.net"
          #"CF_JIRA_EMAIL": "saffi.hartal@codefresh.io"
          
          "CF_GITHUB_TOKEN": ${{ secrets.GIT_TOKEN }}
          
          #this will be derived from the event
          "CF_GIT_PROVIDER": "github"
          "CF_GIT_REPO": "idan-codefresh/example-github-action-use-csdp-report-image"
          "CF_GIT_BRANCH": "main"
          
          "CF_JIRA_MESSAGE": "CR-12293"
          "CF_JIRA_PROJECT_PREFIX": "CR"
        uses: codefresh-io/csdp-report-image@0.0.46




